In [1]:
import numpy as np

### Numpy Array

In [2]:
# numpy da dizi oluşturulabilir.(numpy dizisi)

listem=[20,30,80,75]


In [3]:
type(np.array(listem))

numpy.ndarray

In [4]:
matrixListesi=[[10,20,30],[40,50,60]]

In [5]:
matrixListesi

[[10, 20, 30], [40, 50, 60]]

In [6]:
#Bu şekilde diziyi iki boyutlu hale getirmemizi sağlar.
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60]])

### Arange

In [9]:
# Numpy de default bir dizi oluşturabiliriz

In [9]:
np_dizi=np.arange(0,20,2)

In [10]:
np_dizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace()

In [15]:
#Kendi aralarında eşit dağılmış sayı grubu.
#Burada 
np.linspace(0,20,5)


array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### eye

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random

In [27]:
#float bir dizi oluşturulabilir.
np.random.randn(10)

array([ 2.89366532, -0.10797224, -0.70912119,  0.82307274,  0.6029174 ,
       -0.41712928, -1.17908901,  0.90779836,  0.35531108,  0.57594603])

In [28]:
np.random.randn(2)

array([0.66743641, 0.62370299])

In [29]:
np.random.randn(2,2)

array([[ 3.14402721,  1.36719734],
       [-0.83919337, -0.51609858]])

In [30]:
# int sayı ve dizi  oluşturabilir.

In [31]:
np.random.randint(1,10)

6

In [32]:

np.random.randint(1,10,2)

array([9, 6])

### Numpy Dizi Methodları

In [33]:
numpy_array=np.array(listem)

In [34]:
numpy_array

array([20, 30, 80, 75])

In [35]:
#reshape() methodu diziyi istediğin gibi parçalar.

numpy_array.reshape(2,2)

array([[20, 30],
       [80, 75]])

In [36]:
numpy_array.reshape(4,1)

array([[20],
       [30],
       [80],
       [75]])

In [37]:
numpy_array.min()

20

In [38]:
numpy_array.max()

80

In [42]:
# max sayının kaçıncı indekste olduğunu döndürür.
numpy_array.argmax()

2

In [43]:
#shape özelliği ile güncel dizinin hangi şekle sahip olduğunu döndürülebilir.

reshape_dizi=numpy_array.reshape(2,2)

In [44]:
reshape_dizi

array([[20, 30],
       [80, 75]])

In [45]:
reshape_dizi.shape

(2, 2)