In [1]:
import numpy as np

In [2]:
benim_Dizim=np.arange(0,15)

In [3]:
benim_Dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benim_Dizim[2:5]=-2

In [5]:
benim_Dizim

array([ 0,  1, -2, -2, -2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#Başka bir dizi oluşturucaz ve o diziden bir parça alıp değiştirdiğimizde ana dizi de de değişim olur.

dizi=np.arange(0,20)

In [7]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
slicingDizisi=dizi[4:9]

In [9]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [10]:
slicingDizisi[:]=200

In [11]:
slicingDizisi

array([200, 200, 200, 200, 200])

In [12]:
dizi
#Buradan gördük ki ana dizi de etkilendi.

array([  0,   1,   2,   3, 200, 200, 200, 200, 200,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [13]:
# Bu durumu önlemek için "COPY" kullanılır!

In [14]:
ornekDizi=np.arange(0,30)

In [15]:
ornekDiziCopy=ornekDizi.copy()

In [16]:
ornekDiziCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
slicingislem=ornekDiziCopy[4:10]

In [18]:
slicingislem[:]=1700

In [19]:
slicingislem

array([1700, 1700, 1700, 1700, 1700, 1700])

In [20]:
ornekDiziCopy

array([   0,    1,    2,    3, 1700, 1700, 1700, 1700, 1700, 1700,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29])

In [21]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

##

## Matrix

In [22]:
yeniDizi=[[10,20,30,40],[50,60,70,80]]

In [23]:
yeniDizi

[[10, 20, 30, 40], [50, 60, 70, 80]]

In [24]:
npDizi=np.array(yeniDizi)

In [25]:
npDizi

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [26]:
npDizi[0:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [27]:
npDizi[0:1]

array([[10, 20, 30, 40]])

In [28]:
npDizi[0:,2]
#0. satırdan başla ve 2.indeklerini al

array([30, 70])

In [29]:
npDizi[1:,2:]

array([[70, 80]])

In [30]:
npDizi[1,2]

70

In [31]:
yeniListe=[[20,30,40,50],[60,70,80,90],[100,110,120,130]]

In [32]:
npYeniListe=np.array(yeniListe)

In [33]:
npYeniListe

array([[ 20,  30,  40,  50],
       [ 60,  70,  80,  90],
       [100, 110, 120, 130]])

In [34]:
#Diziden belirli satırları seçer.
npYeniListe[[1,2,0]]

array([[ 60,  70,  80,  90],
       [100, 110, 120, 130],
       [ 20,  30,  40,  50]])

In [35]:
npYeniListe[[0,0,0]]

array([[20, 30, 40, 50],
       [20, 30, 40, 50],
       [20, 30, 40, 50]])

In [36]:
npYeniListe[[1,0,2]]

array([[ 60,  70,  80,  90],
       [ 20,  30,  40,  50],
       [100, 110, 120, 130]])

In [37]:
#Bu yapı ile matristen yeni bir matris üretmiş olduk.

##

### Operasyonlar

In [38]:
benimDizim=np.random.randint(0,100,20)

In [39]:
benimDizim

array([77, 75,  1, 67, 25, 46, 44, 66, 24,  6, 30,  8, 17, 93,  6, 10, 24,
       28, 80, 14])

In [40]:
degerler=benimDizim>50

In [41]:
degerler

array([ True,  True, False,  True, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
        True, False])

In [42]:
 benimDizim[degerler]

array([77, 75, 67, 66, 93, 80])

In [43]:
benimDizim[benimDizim>50]

array([77, 75, 67, 66, 93, 80])

In [44]:
# Diziler arasında toplama,çıkarma,çarpma,bölme olur

In [45]:
sonDizi=np.arange(0,10)

In [46]:
sonDizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
sonDizi*sonDizi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
sonDizi-sonDizi


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
sonDizi/sonDizi

C:\Users\irems\AppData\Local\Temp\ipykernel_9920\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [51]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [52]:
np.max(sonDizi)

9

In [53]:
np.min(sonDizi)

0